language: python

python:
  - "3.7.3"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
script:
  - coverage erase
  - coverage run --source=resumeio/apps manage.py test
  - coverage report -m
  - coveralls
after_success:
  - coveralls