# Generated by Django 3.0.2 on 2020-01-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartresume', '0002_personaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
